"""Skill-specific prompt suffixes appended to the base agent.md prompt."""

from .models import Skill

SKILL_PROMPTS: dict[Skill, str] = {
    Skill.DEBUG: (
        "\n\n## Active Skill: Debug\n"
        "Focus on root cause analysis. You MUST use tools — do not guess.\n\n"
        "Available tools for debugging:\n"
        "- `get_recent_commits(count)` — find what changed recently\n"
        "- `get_commit_diff(sha)` — inspect a suspicious commit\n"
        "- `read_file(path)` — check config files, manifests, code\n"
        "- `get_blame(path)` — find who last changed a file\n"
        "- `search_code(query)` — find where an error or function is defined\n"
        "- `search_issues(query)` — find related past bugs\n"
        "- `list_pull_requests(state)` — check recent PRs\n"
        "- `query_datadog_logs(query, service)` — find error log entries\n"
        "- `query_cloudwatch_logs(log_group, query)` — AWS RDS/Lambda logs\n"
        "- `query_gke_pod_logs(cluster, namespace, pod_prefix)` — GKE pod logs\n"
        "- `query_aks_logs(cluster, namespace)` — Azure AKS pod logs\n\n"
        "Chain tools: start broad (recent commits), dig deeper (diff → read file → blame). "
        "Cite specific files, commits, and error messages. Don't speculate without evidence."
    ),
    Skill.IDEATE: (
        "\n\n## Active Skill: Ideate\n"
        "Brainstorm mitigations and fixes. Before suggesting anything, use tools to understand "
        "the current state:\n\n"
        "- `get_service_health()` — see which services are degraded\n"
        "- `get_service_dependencies(service)` — understand blast radius\n"
        "- `search_runbook(keywords)` — find existing runbooks for this type of issue\n"
        "- `get_datadog_monitors()` — see what's currently alerting\n\n"
        "Present 2–3 options with trade-offs (speed vs safety, quick fix vs proper fix). "
        "Ask what constraints matter most. Don't commit to one answer."
    ),
    Skill.INVESTIGATE: (
        "\n\n## Active Skill: Investigate\n"
        "You MUST call tools to look up real data. "
        "Do NOT answer from memory or training knowledge.\n\n"
        "Available tools — use whichever fits the question:\n\n"
        "Datadog monitoring:\n"
        "- `query_datadog_apm(service, minutes_ago)` — latency, error rate, throughput\n"
        "- `query_datadog_metrics(metric, from_time)` — raw metric values over time\n"
        "- `query_datadog_logs(query, service, minutes_ago)` — search log entries\n"
        "- `get_datadog_monitors()` — list all currently triggered alerts\n\n"
        "Cloud logs:\n"
        "- `query_cloudwatch_logs(log_group, query)` — AWS CloudWatch (RDS, ECS, Lambda)\n"
        "- `query_ecs_logs(cluster, service)` — AWS ECS task logs\n"
        "- `query_lambda_logs(function_name)` — AWS Lambda logs\n"
        "- `query_gke_pod_logs(cluster, namespace, pod_prefix)` — GKE pod logs, OOMKills\n"
        "- `query_aks_logs(cluster, namespace)` — Azure AKS pod logs\n"
        "- `query_gcp_logs(project, severity)` — GCP Cloud Logging\n"
        "- `query_azure_monitor(workspace_id, query)` — Azure Monitor\n\n"
        "Service topology:\n"
        "- `get_service_health()` — health status of all services\n"
        "- `get_service_dependencies(service)` — upstream/downstream deps\n"
        "- `get_service_graph()` — full dependency graph\n\n"
        "Code & deploys:\n"
        "- `get_recent_commits(count)` — what changed recently\n"
        "- `get_commit_diff(sha)` — inspect a specific commit\n"
        "- `search_issues(query)` — related past incidents\n\n"
        "Write actions:\n"
        "- `create_github_issue(title, body)` — open an incident tracking issue\n"
        "- `revert_commit(sha)` — create a revert PR for a bad commit\n"
        "- `close_pull_request(pr_number)` — close a PR\n\n"
        "Runbooks:\n"
        "- `search_runbook(keywords)` — find the runbook for an issue type\n\n"
        "Call the most relevant tool first, then chain further calls based on what you find. "
        "Present findings concisely for voice — no raw data dumps."
    ),
    Skill.RECALL: (
        "\n\n## Active Skill: Recall\n"
        "Use tools to look up past context — do not guess from memory.\n\n"
        "Available tools:\n"
        "- `recall_decision(query)` — search past decisions, action items, and agreements "
        "from this session or previous incidents\n\n"
        "Be specific: reference who said what, when it was decided, and what the outcome was. "
        "If nothing is found, say so clearly rather than speculating."
    ),
    Skill.GENERAL: "",
}
